[package]
name = "functional-tests"
version = "0.1.0"
edition = "2021"
authors = ["Adrian Utrilla <adrianutrilla@gmail.com>"]

[dependencies]
tempdir = "0.3.5"
serde = "1.0"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
serde_derive = "1.0"
lazy_static = "1.5.0"
