name: "Docs"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    # Only consider changes to documentation
    paths:
      - '**/*.md'
      - '**/*.rst'
      - '**/*.txt'
  schedule:
    - cron: '25 6 * * 3'

permissions:
  contents: read

jobs:
  documentation:
    name: Lint RST and MD files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.0.0

      - name: Install rstcheck and markdownlint
        run: |
          pip install rstcheck
          sudo gem install mdl

      - name: Run rstcheck on all RST files
        run: make checkrst

      - name: Run mdl on all MD files
        run: make checkmd
